CREATE SCHEMA IF NOT EXISTS APP;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID VARCHAR NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP
 )