server: 
  port: 8081
web:
  cors: 
    allowed-origins: "*"    
spring:
  application:
    name: api-gateway
  boot:
    admin:
      client:
        url: lb://CONFIG-SERVER
  cloud:
    gateway:
      routes:
        - id: customers_route
          uri: lb://customers-service
          predicates: 
          - Path=/api/customers/**
        - id: orders_route
          uri: lb://orders-service
          predicates: 
          - Path=/api/orders/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"          
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
