server:
  port: 8082
  contextPath: /api
web:
  cors: 
    allowed-origins: "http://localhost:8081"  
logging:
  level:
    root: INFO
    org:
      springframework:
        http.server.reactive: DEBUG
        web.reactive: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: customers-service