server:
  port: 8082
web:
  cors: 
    allowed-origins: "http://localhost:8081"  
logging:
  level:
    root: INFO
    org:
      springframework:
        http.server.reactive: DEBUG
        web.reactive: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: customers-service
  boot:
    admin:
      client:
        url: lb://CONFIG-SERVER
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
flyway:
  user: sa
  password: password
  schemas: APP
  url: jdbc:h2:mem:testdb
  locations: classpath:db/migrations
management:
  endpoints:
    web:
      exposure:
        include: '*'
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces