server:
  port: 8888
spring:
  application:
    name: config-server
  management:
    endpoints:
      web:
        exposure:
          include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
